### ISSUE TITLE
Converting tf_efficientnet_lite1 to ONNX

### ISSUE THREAD

**Issue by kedardg** [rwightman/gen-efficientnet-pytorch#34]
Is there a way around or a solution?

 C:\Users\Kedar/.cache\torch\hub\rwightman_gen-efficientnet-pytorch_master\geffnet\conv2d_layers.py:39: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  return max((math.ceil(i / s) - 1) * s + (k - 1) * d + 1 - i, 0)
C:\Users\Kedar/.cache\torch\hub\rwightman_gen-efficientnet-pytorch_master\geffnet\conv2d_layers.py:39: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  return max((math.ceil(i / s) - 1) * s + (k - 1) * d + 1 - i, 0)
C:\Users\Kedar/.cache\torch\hub\rwightman_gen-efficientnet-pytorch_master\geffnet\conv2d_layers.py:63: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if pad_h > 0 or pad_w > 0:
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "C:\Users\Kedar\.conda\envs\conv\lib\site-packages\torch\onnx\__init__.py", line 148, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "C:\Users\Kedar\.conda\envs\conv\lib\site-packages\torch\onnx\utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "C:\Users\Kedar\.conda\envs\conv\lib\site-packages\torch\onnx\utils.py", line 416, in _export
    fixed_batch_size=fixed_batch_size)
  File "C:\Users\Kedar\.conda\envs\conv\lib\site-packages\torch\onnx\utils.py", line 296, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "C:\Users\Kedar\.conda\envs\conv\lib\site-packages\torch\onnx\utils.py", line 135, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "C:\Users\Kedar\.conda\envs\conv\lib\site-packages\torch\onnx\__init__.py", line 179, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "C:\Users\Kedar\.conda\envs\conv\lib\site-packages\torch\onnx\utils.py", line 657, in _run_symbolic_function
    return op_fn(g, *inputs, **attrs)
  File "C:\Users\Kedar\.conda\envs\conv\lib\site-packages\torch\onnx\symbolic_helper.py", line 128, in wrapper
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "C:\Users\Kedar\.conda\envs\conv\lib\site-packages\torch\onnx\symbolic_helper.py", line 128, in <listcomp>
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "C:\Users\Kedar\.conda\envs\conv\lib\site-packages\torch\onnx\symbolic_helper.py", line 81, in _parse_arg
    "', since it's not constant, please try to make "
RuntimeError: Failed to export an ONNX attribute 'onnx::Div', since it's not constant, please try to make things (e.g., kernel size) static if possible

**Comment by rwightman** [comment]
It works fine for me in Onnx 1.5, pretty sure I tested 1.6 at some point as well. Did you use my export script, if not you have to at least follow the sequence of ops that I do for the TF models with SAME padding. 

You must call `geffnet.config.set_exportable(True)` before creating the model. 

And, after creating the model, but before exporting, you must run at least one batch through the at the correct input size to create the static 'SAME' padding layers. You must also export the model with a fixed image size, you cannot leave the image dim dynamic with the TF models.

```
 x = torch.randn((1, 3, args.img_size or 224, args.img_size or 224), requires_grad=True)
 model(x)  # run model once before export trace
```
