### ISSUE TITLE
torch.jit.script(model) crashed

### ISSUE THREAD

**Issue by devymex** [rwightman/gen-efficientnet-pytorch#52]
```
torch.hub.list('rwightman/gen-efficientnet-pytorch')
model = torch.hub.load('rwightman/gen-efficientnet-pytorch', 'efficientnet_b0', pretrained=True, num_classes=3)
scriptedmodel = torch.jit.script(model)
```

got:

```
=> Discarding pretrained classifier since num_classes != 1000
Traceback (most recent call last):
  File "./scripts/update_model.py", line 122, in <module>
    scriptedmodel = torch.jit.script(model)
  File "/home/security/.local/lib/python3.8/site-packages/torch/jit/__init__.py", line 1516, in script
    return torch.jit._recursive.create_script_module(obj, torch.jit._recursive.infer_methods_to_compile)
  File "/home/security/.local/lib/python3.8/site-packages/torch/jit/_recursive.py", line 318, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/security/.local/lib/python3.8/site-packages/torch/jit/_recursive.py", line 372, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/security/.local/lib/python3.8/site-packages/torch/jit/__init__.py", line 1900, in _construct
    init_fn(script_module)
  File "/home/security/.local/lib/python3.8/site-packages/torch/jit/_recursive.py", line 353, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, infer_methods_to_compile)
  File "/home/security/.local/lib/python3.8/site-packages/torch/jit/_recursive.py", line 376, in create_script_module_impl
    create_methods_from_stubs(concrete_type, stubs)
  File "/home/security/.local/lib/python3.8/site-packages/torch/jit/_recursive.py", line 292, in create_methods_from_stubs
    concrete_type._create_methods(defs, rcbs, defaults)
  File "/home/security/.local/lib/python3.8/site-packages/torch/jit/annotations.py", line 290, in try_ann_to_type
    torch.jit._recursive_compile_class(ann, loc)
  File "/home/security/.local/lib/python3.8/site-packages/torch/jit/__init__.py", line 1359, in _recursive_compile_class
    _compile_and_register_class(obj, rcb, _qual_name)
  File "/home/security/.local/lib/python3.8/site-packages/torch/jit/__init__.py", line 1363, in _compile_and_register_class
    _jit_script_class_compile(qualified_name, ast, rcb)
RuntimeError: 
Tried to access nonexistent attribute or method 'saved_tensors' of type '__torch__.geffnet.activations.activations_me.SwishJitAutoFn'. Did you forget to initialize an attribute in __init__()?:
  File "/home/security/.cache/torch/hub/rwightman_gen-efficientnet-pytorch_master/geffnet/activations/activations_me.py", line 50
    @staticmethod
    def backward(ctx, grad_output):
        x = ctx.saved_tensors[0]
            ~~~~~~~~~~~~~~~~~ <--- HERE
        return swish_jit_bwd(x, grad_output)
'SwishJitAutoFn.backward' is being compiled since it was called from '__torch__.geffnet.activations.activations_me.SwishJitAutoFn'
  File "/home/security/.cache/torch/hub/rwightman_gen-efficientnet-pytorch_master/geffnet/activations/activations_me.py", line 63
    def forward(self, x):
        return SwishJitAutoFn.apply(x)
               ~~~~~~~~~~~~~~ <--- HERE
'__torch__.geffnet.activations.activations_me.SwishJitAutoFn' is being compiled since it was called from 'SwishMe.forward'
  File "/home/security/.cache/torch/hub/rwightman_gen-efficientnet-pytorch_master/geffnet/activations/activations_me.py", line 63
    def forward(self, x):
        return SwishJitAutoFn.apply(x)
               ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
```

**Comment by devymex** [comment]
fixed.

```

#class SwishMe(nn.Module):
#    def __init__(self, inplace: bool = False):
#        super(SwishMe, self).__init__()
#    def forward(self, x):
#        return SwishJitAutoFn.apply(x)

class SwishMe(nn.Module):
    def __init__(self, inplace: bool = False):
        super(SwishMe, self).__init__()

    def forward(self, x):
        return x * torch.sigmoid(x)


```

**Comment by rwightman** [comment]
@devymex that's what the scriptable argument in the create_model factory is for, as used in example validation script
